version: 0.2

phases:
  build:
    commands:
      - n 20.9.0
      - node -v
      - npm -v
      - npm install -g @angular/cli
      - cd frontend
      - npm install
      - ng build --prod
      - cd ../backend
      - npm install
