version: 0.2

phases:
  build:
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - source "$NVM_DIR/nvm.sh"  # Carrega o NVM
      - nvm -v  # Verifica se o nvm está disponível
      - rm -rf "$NVM_DIR"  # Remove o diretório nvm
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash  # Instala o nvm novamente
      - export NVM_DIR="$HOME/.nvm"
      - source "$NVM_DIR/nvm.sh"  # Carrega o NVM novamente
      - nvm install 18.13
      - node -v  # Exibe a versão do Node.js para fins de depuração
      - npm install -g @angular/cli
      - cd frontend
      - npm install
      - ng build --prod
      - cd ../backend
      - npm install
