version: 0.2

phases:
  build:
    commands:
      - node -v
      - npm -v
      - rm /usr/local/bin/n || true
      - npm list -g n || npm install -g n
      - node -v
      - npm -v
      - npm install -g @angular/cli
      - cd frontend
      - npm install
      - npm run build
      - cd ../backend
      - npm install
