version: 0.2

phases:
  build:
    commands:
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  #Carrega o NVM
      - nvm install 18.13
      - nvm use 18.13
      - npm install -g @angular/cli
      - cd frontend
      - npm install
      - ng build --prod
      - cd ../backend
      - npm install
